[package]
name = "game-detection"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
once_cell = "1.19"
parking_lot = "0.12"
wmi = "0.13"
serde = { version = "1.0", features = ["derive"] } # <-- "derive" ÇOK ÖNEMLİ
